# azure-pipelines.yml
trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection
  dockerRegistryServiceConnection: 'b7697af7-b180-4ac7-bbba-b025f0d3bcdd'
  imageRepository: 'pawfectfindfrontend'
  containerRegistry: 'pawfectfind.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Web App settings - UPDATE THESE!
  webAppName: 'pawfectfind'  # Your actual Web App name
  resourceGroup: 'PawfectFind-RG'         # Your resource group name
  azureSubscription: 'pawfectfind-azure'  # Azure service connection name

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: 
      vmImage: 'ubuntu-latest'  # or 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest  # ADDED: Also tag as latest

- stage: Deploy
  displayName: Deploy to Web App
  dependsOn: Build
  condition: succeeded()
  
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure Web App
    environment: 'production'
    pool: 
      vmImage: 'ubuntu-latest'  # or 'windows-latest'
    
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(webAppName)'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              resourceGroupName: '$(resourceGroup)'